-- Vector CRM feature expansions (jobsite readiness, loadout verification, time logs, updates, change orders)

-- Multi-tenant organizations
create table if not exists orgs (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  default_project_type text,
  created_at timestamptz default now()
);

-- Jobsite readiness checklist
create table if not exists jobsite_readiness (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  checklist jsonb default '{}'::jsonb,
  notes text,
  updated_at timestamptz default now()
);

-- Crew time tracking
create table if not exists time_entries (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  person_id bigint references people(id) on delete set null,
  work_date date,
  hours numeric,
  notes text,
  created_at timestamptz default now()
);

-- Client-facing status updates
create table if not exists project_updates (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  status text,
  message text,
  author_id bigint references people(id) on delete set null,
  created_at timestamptz default now()
);

-- Automations (workflow builder)
create table if not exists automations (
  id text primary key,
  org_id bigint references orgs(id) on delete cascade,
  name text,
  folder text,
  status text,
  "triggerType" text,
  "triggerValue" text,
  "offsetDays" integer,
  channel text,
  audience text,
  subject text,
  message text,
  "aiEnabled" boolean default false,
  "aiPrompt" text,
  "updatedAt" timestamptz default now()
);

create index if not exists automations_org_idx on automations (org_id);

create table if not exists automation_folders (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  unique (org_id, name)
);

create index if not exists automation_folders_org_idx on automation_folders (org_id);

-- Change orders
create table if not exists change_orders (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  title text,
  description text,
  amount numeric,
  status text,
  requested_by bigint references people(id) on delete set null,
  approved_by bigint references people(id) on delete set null,
  created_at timestamptz default now()
);

-- Loading sheet verification fields
alter table loading_sheets add column if not exists loadout_checks jsonb default '{}'::jsonb;
alter table loading_sheets add column if not exists verified_by_id bigint;
alter table loading_sheets add column if not exists verified_at timestamptz;

-- Punchlist additions (RFI, returns, follow-ups)
alter table punchlist add column if not exists followup_date date;
alter table punchlist add column if not exists followup_assigned_id bigint;
alter table punchlist add column if not exists eta_date date;
alter table punchlist add column if not exists rma_number text;
alter table punchlist add column if not exists photo_tags text[];

-- Shipment lead-time / vendor tracking
alter table shipments add column if not exists vendor text;
alter table shipments add column if not exists lead_time_days int;
alter table shipments add column if not exists eta_date date;
alter table shipments add column if not exists po_status text;

-- Project PM access list
alter table projects add column if not exists pm_emails text[];

-- Project type (install vs move)
alter table projects add column if not exists project_type text;

-- Move checklists
create table if not exists move_checklists (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  checklist jsonb default '{}'::jsonb,
  notes jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

-- Move inventory
create table if not exists move_items (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  name text,
  quantity int,
  category text,
  pickup_location text,
  drop_location text,
  is_high_value boolean default false,
  qr_code text,
  qr_data_url text,
  picked boolean default false,
  arrived boolean default false,
  notes text,
  before_photos text[],
  after_photos text[],
  verified_by_id bigint references people(id) on delete set null,
  verified_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Surveys (room-by-room)
create table if not exists surveys (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  status text,
  scheduled_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists survey_rooms (
  id bigint generated by default as identity primary key,
  survey_id bigint references surveys(id) on delete cascade,
  name text,
  floor text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists survey_items (
  id bigint generated by default as identity primary key,
  room_id bigint references survey_rooms(id) on delete cascade,
  name text,
  quantity int,
  category text,
  notes text,
  is_high_value boolean default false,
  photos text[],
  labor_factor numeric,
  created_at timestamptz default now()
);

-- Quotes
create table if not exists quotes (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  version int,
  status text,
  subtotal numeric,
  tax numeric,
  total numeric,
  created_at timestamptz default now(),
  approved_at timestamptz,
  expires_at date,
  signed_name text,
  signed_email text,
  signed_at timestamptz,
  signature_data text
);

create table if not exists quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint references quotes(id) on delete cascade,
  name text,
  qty numeric,
  unit_price numeric,
  line_total numeric,
  category text
);

-- Quote share links (link-only quote access, 30-day expiration)
create table if not exists quote_share_links (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  quote_id bigint references quotes(id) on delete cascade,
  expires_at date not null,
  revoked_at timestamptz,
  created_at timestamptz default now(),
  last_viewed_at timestamptz,
  view_count int default 0
);

create index if not exists quote_share_links_org_idx on quote_share_links (org_id);
create index if not exists quote_share_links_quote_idx on quote_share_links (quote_id);
create unique index if not exists quote_share_links_active_unique on quote_share_links (quote_id) where revoked_at is null;

-- Move milestones, access, labels, materials
create table if not exists move_milestones (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  stage text,
  status text,
  due_date date,
  updated_at timestamptz default now()
);

create table if not exists move_access (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  location text,
  contact_name text,
  contact_phone text,
  contact_email text,
  dock_reservation text,
  elevator_reservation text,
  coi_status text,
  notes text,
  updated_at timestamptz default now()
);

create table if not exists move_labels (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  code text,
  zone text,
  destination text,
  color text,
  qr_data_url text,
  created_at timestamptz default now()
);

create table if not exists move_materials (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  name text,
  planned_qty numeric,
  actual_qty numeric,
  unit_cost numeric,
  total_cost numeric,
  updated_at timestamptz default now()
);

-- Completion sign-off fields
alter table project_completions add column if not exists signoff_name text;
alter table project_completions add column if not exists signoff_title text;
alter table project_completions add column if not exists signoff_email text;
alter table project_completions add column if not exists signoff_confirmed boolean;
alter table project_completions add column if not exists signoff_at timestamptz;

-- Org scoping
alter table clients add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table people add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table projects add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table scans add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table scan_inbox add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table shipments add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table punchlist add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table dispatches add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table loading_sheets add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table project_completions add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table jobsite_readiness add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table time_entries add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table project_updates add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table change_orders add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_checklists add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_items add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table surveys add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table survey_rooms add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table survey_items add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table quotes add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table quote_items add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_milestones add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_access add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_labels add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table move_materials add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table staff_roles add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table staff_permissions add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table users add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table integrations add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table warehouse_rows add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table warehouse_bays add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table warehouse_bins add column if not exists org_id bigint references orgs(id) on delete cascade;
alter table inventory_items add column if not exists org_id bigint references orgs(id) on delete cascade;
