-- Trigger.dev execution tracking tables
-- Run this in Supabase SQL editor AFTER the base schema_updates.sql

-- ============================================================
-- Workflow Events (CRM emits these → Trigger.dev consumes)
-- ============================================================
create table if not exists workflow_events (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  event_type text not null,         -- e.g. lead.created, pipeline.stage_changed
  entity_type text not null,        -- e.g. project, quote, contact
  entity_id text,                   -- ID of the entity that triggered the event
  payload jsonb default '{}'::jsonb, -- full event payload
  created_at timestamptz default now(),
  processed_at timestamptz          -- set when Trigger.dev processes it
);

create index if not exists workflow_events_org_idx on workflow_events (org_id);
create index if not exists workflow_events_type_idx on workflow_events (event_type);
create index if not exists workflow_events_unprocessed_idx on workflow_events (processed_at) where processed_at is null;

-- ============================================================
-- Workflow Runs (one row per automation execution)
-- ============================================================
create table if not exists workflow_runs (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  automation_id text references automations(id) on delete cascade,
  event_id bigint references workflow_events(id) on delete set null,
  status text default 'pending',    -- pending, running, completed, failed
  error text,
  started_at timestamptz default now(),
  completed_at timestamptz
);

create index if not exists workflow_runs_org_idx on workflow_runs (org_id);
create index if not exists workflow_runs_auto_idx on workflow_runs (automation_id);
create index if not exists workflow_runs_status_idx on workflow_runs (status);

-- ============================================================
-- Workflow Run Steps (one row per step executed in a run)
-- ============================================================
create table if not exists workflow_run_steps (
  id bigint generated by default as identity primary key,
  run_id bigint references workflow_runs(id) on delete cascade,
  step_id bigint references workflow_steps(id) on delete set null,
  step_order int,
  step_type text,
  action_type text,
  status text,                      -- completed, failed, skipped
  result jsonb default '{}'::jsonb,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists workflow_run_steps_run_idx on workflow_run_steps (run_id);

-- ============================================================
-- Messages (SMS / email history for all orgs)
-- ============================================================
create table if not exists messages (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  direction text,                   -- inbound, outbound
  from_number text,
  to_number text,
  body text,
  status text,                      -- queued, sent, delivered, failed, received
  channel text default 'sms',       -- sms, email, whatsapp
  twilio_sid text,
  contact_id bigint,
  automation_id text,
  error_code text,
  error_message text,
  media_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists messages_org_idx on messages (org_id);
create index if not exists messages_contact_idx on messages (contact_id);
create index if not exists messages_twilio_sid_idx on messages (twilio_sid);
create index if not exists messages_direction_idx on messages (direction);

-- ============================================================
-- Conversations (thread SMS by contact + org)
-- ============================================================
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  contact_id bigint,
  phone_number text,
  last_message_at timestamptz,
  last_message_preview text,
  unread_count int default 0,
  status text default 'open',       -- open, closed, snoozed
  created_at timestamptz default now()
);

create index if not exists conversations_org_idx on conversations (org_id);
create index if not exists conversations_contact_idx on conversations (contact_id);

-- ============================================================
-- Tasks (created by automations or manually)
-- ============================================================
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  org_id bigint references orgs(id) on delete cascade,
  title text,
  description text,
  due_date date,
  status text default 'pending',    -- pending, in_progress, completed
  entity_type text,                 -- project, quote, contact
  entity_id text,
  assigned_to text,                 -- user email or ID
  completed_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists tasks_org_idx on tasks (org_id);
create index if not exists tasks_status_idx on tasks (status);
create index if not exists tasks_due_idx on tasks (due_date);
